default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USERNAME'] || 'postgres' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  password: <%= ENV['POSTGRES_HOST'] || 'postgres' %>

development:
  <<: *default
  database: salesloft_integration_api_development
  username: <%= ENV['POSTGRES_USERNAME'] || 'postgres' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %>

production:
  url: <%= ENV['DATABASE_URL'] %>
